### ISSUE TITLE
数据除错

### ISSUE THREAD

**Issue by vokins** [sy618/hosts#1]
127.0.0.1 ynuf.alipay.com
127.0.0.1 wb.110.taobao.com
像这样的都是支付宝淘宝的没必要屏蔽啊。

**Comment by vokins** [comment]
127.0.0.1 cn.gravatar.com
这个是头像的域名
127.0.0.1 hiphotos.baidu.com
这是百度图像的域名

**Comment by sy618** [comment]
感谢你的反馈，这些都是在尝试屏蔽“今日头条”时产生的误杀，现已去除所有修改内容。
平时我都不上github，所以看不到有人反馈。大本营在“酷安市场「adaway中国版」软件的评论里，在那里可以找到我，或者加微信交流群。
