### ISSUE TITLE
FQ与racaljk

### ISSUE THREAD

**Issue by panyuhang93** [sy618/hosts#12]
这两个可以共用吗

**Comment by sy618** [comment]
不可以，因为重复了。
FQ属于我独立维护的数据，你对比一下就能知道。
所以我写了两种方案供大家选择。
如果你使用方案一后遇到域名缺失、IP失效、未收录等情况可以反馈给我解决。
使用方案二遇到问题那么请直接到racaljk那边反馈。

**Comment by sy618** [comment]
不可以，因为重复了。
FQ属于我独立维护的数据，你对比一下就能知道。
所以我写了两种方案供大家选择。
如果你使用方案一后遇到域名缺失、IP失效、未收录等情况可以反馈给我解决。
使用方案二遇到问题那么请直接到racaljk那边反馈。
