### ISSUE TITLE
【功能建议】添加 Hosts Tool 小工具

### ISSUE THREAD

**Issue by catshitz** [sy618/hosts#13]
输数字选方案，自动更新hosts文件，方便不能使用路由器自动更新的PC端。

**Comment by sy618** [comment]
PC端可以使用这个软件来更新hosts：
https://raw.githubusercontent.com/vokins/yhosts/master/win/uphosts.exe 
这个软件是群友开发的，可放心使用。

**Comment by catshitz** [comment]
非常感谢！
