### ISSUE TITLE
无法登陆console.cloud.google.com

### ISSUE THREAD

**Issue by gameclamp** [sy618/hosts#14]
这个域名没在列表里。

**Comment by sy618** [comment]
还有发现其他缺失的域名吗？

**Comment by sy618** [comment]
通过抓包，我添加了以下缺少的域名：
ssh.cloud.google.com
console.cloud.google.com
cloudusersettings-pa.clients6.google.com
servicemanagement.clients6.google.com
cloudconsole-pa.clients6.google.com
是否还有漏掉的还请你抓包看看。

如果你是WiFi环境下，建议使用dnsmasq方案，在路由器上部署dnsmasq规则，应该就不会存在缺失域名的情况了。
