### ISSUE TITLE
firefox，youtube内容不能播放

### ISSUE THREAD

**Issue by liuxb** [sy618/hosts#18]
使用了f，p，y三个host，界面可以出来，内容不能播放。
好像每次都会连接三个googlevideo.com地址，其中两个在y这个host中有，另外一个就没有，不知道是不是这个原因？
比如
r3---sn-hp57kn7e.googlevideo.com
r5---sn-5ualdn7k.googlevideo.com
这两个就没有收录，这种地址是随机的吧，怎么尽可能收录全？

**Comment by sy618** [comment]
YouTube视频的sn域名其实是有规律的，使用的是按地区机场编码。
详细：https://github.com/lennylxx/ipv6-hosts/wiki/YouTube#4-sn-%E7%BC%96%E7%A0%81%E5%9C%B0%E5%9D%80

由于hosts不支持通配符，这些sn域名是没法收录全，也没必要收录全，我们只需要收录IP对应地区的编码就够用了。
另外，dnsmasq规则支持通配符，也就解决了这问题。

**Comment by sy618** [comment]
建议你直接用这个合并好的数据（相当于f+p+y）
https://raw.githubusercontent.com/sy618/hosts/master/FQ

或者使用方案二。

**Comment by liuxb** [comment]
谢谢，
使用了FQ这个可以了，内容比f+p+y要多多了。
但是vokins+f（看了里面没有涉及到youtube的）+p+y，也就是方案1，仍然不能播放youtube，vokins里面youtube相关域名IP和FQ这个里面的不一致，不知道是不是这个原因？

**Comment by sy618** [comment]
“f”仅是部分FQ数据。
这个FQ hosts项目这么久了也就我一个人在维护，我已经不指望多人一起维护了。所以一些容易被封的数据就没直接发出来。
你可以照着两个方案的说明来订阅使用即可（方案一是两个源）。或者直接用方案二的四个源。

而dnsmasq规则是开源的，比hosts更强大，不过我看也是没几个人在用。
这个项目我主要是给个人用户使用的，非盈利性质。
更多交流可以加群。
