### ISSUE TITLE
FQ 2103行有个乱码

### ISSUE THREAD

**Issue by xiesunny** [sy618/hosts#19]
z-1-scontent 后面有个乱码
31.13.93.15 z-1-scontent.xx.fbcdn.net

**Comment by sy618** [comment]
不会啊，你可以用网页打开看看，并没有乱码。
hosts 是在UTF-8 文本编码下编辑的。

**Comment by xiesunny** [comment]
用Chrome浏览器可以看出来，或者你使用一些下载工具直接下载原始文件到本地电脑上查看也可以看到。
https://raw.githubusercontent.com/sy618/hosts/master/FQ
z-1-scontent后面有一个字节是二进制0x02，这个在Chrome上会是乱码。
使用AdAway更新hosts到手机上，因为这个乱码会导致这行被丢弃。

**Comment by sy618** [comment]
这个问题应该是解决了
