### ISSUE TITLE
uphosts.exe把我自己添加的记录给删了。

### ISSUE THREAD

**Issue by tqangxl** [sy618/hosts#21]
你做的的这很不错

我看这个的工具不会删除用户的添加的记录。你可以参考下
https://coding.net/u/scaffrey/p/hosts/git

###	::1             localhost

**0.0.0.0 account.jetbrains.com** 

### https://creativecommons.org/licenses/by-nc-sa/4.0/

**# Modified Hosts Start**

### Localhost (DO NOT REMOVE) Start
127.0.0.1	localhost

**Comment by sy618** [comment]
uphosts.exe这个软件是由群友开发的，有问题可以找他解决。
酷安：
http://www.coolapk.com/u/620885

**Comment by oldmannish** [comment]
把自己的hosts放到附加.txt
