### ISSUE TITLE
建議添加

### ISSUE THREAD

**Issue by OvlTkm** [sy618/hosts#22]
`31.192.120.36 www.pornhub.com`
`31.192.120.36 pornhub.com`
`104.16.3.16 www.wattpad.com`
`54.83.5.150 wattpad.com`
`104.16.2.16 a.wattpad.com`
`104.16.2.16 em.wattpad.com`
`205.203.132.65 wsj.com`
`54.230.192.94 www.wsj.com`
`205.203.133.8 buy.wsj.com`
`23.15.8.128 cn.wsj.com`
//手動滑稽

**Comment by sy618** [comment]
https://www.pornhub.com/
这个没被DNS污染，加https可直接打开。/跟风滑稽

**Comment by OvlTkm** [comment]
我這裡好像被污染了🌚🌚🌚

**Comment by sy618** [comment]
wattpad这个又是什么？

**Comment by OvlTkm** [comment]
左轉進入維基百科
https://en.m.wikipedia.org/wiki/Wattpad
大概是個發小說之類的網站

**Comment by sy618** [comment]
华尔街日报这个网站没有SSL加密，所以容易被连接重置。这个就不合并了，暂时放到/data数据里。
wattpad也放到/data数据里。

主数据只加Pornhub。

**Comment by sy618** [comment]
https://github.com/sy618/hosts/tree/master/data

**Comment by OvlTkm** [comment]
好的
（不過WSJ的中文版沒有SSL英文版是有的）
