### ISSUE TITLE
easyhosts youtube规则 引用许可请求

### ISSUE THREAD

**Issue by forkgood** [sy618/hosts#24]
项目：easyhosts
Github：https://github.com/forkgood/easyhosts
项目主页：https://windows.cat
由于程序自动更新，我的项目会使用到您更新的PCCW香港代理IP的youtube项目规则，留意到使用您的项目需要得到许可，所以发此Issues征求同意。

期待您的回答，如果因任何些原因，无法允许其他项目进行整合，您做出决定后我们会及时取消使用，感谢！: D

**Comment by sy618** [comment]
没问题，随你用！
任何人只要在这里打声招呼后随便你用！
另外你的dnsmasq规则是直接转换的，效率不高。而且也没有充分利用dnsmasq规则的泛解析特性。可以参考一下https://raw.githubusercontent.com/sy618/hosts/master/dnsmasq/dnsfq1

**Comment by forkgood** [comment]
dnsmasq规则目前正在在做自动更新上的调整，会用到泛解析，感谢指点答复。

祝每天好运！
