### ISSUE TITLE
我很无奈

### ISSUE THREAD

**Issue by uchen1225** [sy618/hosts#27]
首先，我很抱歉在这里说这事。但不得不说。
你群里有些自以为大佬的管理感觉自己很强，很硬，很牛逼，没犯群规，随意踢人。
我想真正的大佬不会介意小白再白痴的问题，所以恳请麻烦管管。
请原谅我，如果我说错什么了的话。

**Comment by sy618** [comment]
你什么ID ？

**Comment by sy618** [comment]
这个QQ群是为了维护hosts数据而存在，主要是让人贡献数据的。
并没有要看不起“小白”的意思，毕竟我们也都是从小白过来的。但太基础的问题我们是无法很好交流的，也实在没精力去教。
建议你可以去酷安等开放社区学习！
