### ISSUE TITLE
自动更新问题

### ISSUE THREAD

**Issue by wst4288** [sy618/hosts#30]

**Comment by wst4288** [comment]
想问一下，安卓机子怎么自动更新hosts呀，看不太懂。
还有 adfq为什么不更新了呀

**Comment by sy618** [comment]
你可以去研究一下安卓tasker这个软件。下载脚本并把脚本导入还原即可。

ADFQ这个我认为已经没有存在的意义了。
分开下载你就可以获得最新数据而不必等我合并更新。
