### ISSUE TITLE
TASKER 问题

### ISSUE THREAD

**Issue by wst4288** [sy618/hosts#31]
谢谢作者的回复。
我下载了tasker ，点击还原的时候并不能选择文件，而是提示无可还原文件，该怎么解决呢，谢谢。

**Comment by sy618** [comment]
使用说明.txt已经说的很清楚了。
自己研究下～

**Comment by wst4288** [comment]
已经成功了！

**Comment by wst4288** [comment]
不过不是自动 是手动🤣
