### ISSUE TITLE
Google已失效

### ISSUE THREAD

**Issue by caryle** [sy618/hosts#33]
山东联通，Google play，YouTube，drive等失效

**Comment by bdzyq** [comment]
我重庆移动，没问题。

**Comment by WA-YI** [comment]
北京联通，没问题。

**Comment by SamsungGoogle3** [comment]
大神 请问怎么制作hosts文件

**Comment by andy19801210** [comment]
@SamsungGoogle3 问的好我也想知道。

_Sent from my 360 1505-A02 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SamsungGoogle3** [comment]
shadowsocks-libev有这个软件吗？

**Comment by SamsungGoogle3** [comment]
@andy19801210 有吗？
