### ISSUE TITLE
希望增加telegram

### ISSUE THREAD

**Issue by viceyy** [sy618/hosts#34]
一直在用大大的hosts,不仅更新及时，速度也很快，但是没有telegram，希望能够添加，非常感谢

**Comment by sy618** [comment]
tg的app（Android or iOS）是通过IP直连的，无需经过hosts解析。所以没办法。
目前hosts里只加了telegram.org域名用于打开邀请链接。

**Comment by viceyy** [comment]
哦，原来是这样，麻烦了

**Comment by sy618** [comment]
写了个免翻直连telegram的解决方案：
https://github.com/sy618/hosts/blob/master/md/telegram.md
