### ISSUE TITLE
Twitter无法访问。

### ISSUE THREAD

**Issue by PIRASHIN** [sy618/hosts#38]
![snipaste_20170803_183558](https://user-images.githubusercontent.com/30690790/28918091-9dca5296-787a-11e7-9b21-c4689a307b0b.png)

**Comment by woyaojizhu8** [comment]
找了好多sni都是，能代其他，唯独不能代小鸟，这是为什么呢？

**Comment by sy618** [comment]
因为健身哥。 
朝廷花大力气用来阻断小鸟，在你与小鸟第一次握手阶段立刻就收到RST连接重置的伪装包结束通信。
