### ISSUE TITLE
希望把resilio sync的加进去

### ISSUE THREAD

**Issue by zheshiyigehaomingzi** [sy618/hosts#39]
54.230.143.112  config.getsync.com config.resilio.com

**Comment by sy618** [comment]
这两个hosts实际上早已经加了。但没用的。

btsync非去中心化，其工作时需要tracker服务器来指引节点。
现在btsync依旧用不了是因为两个tracker服务器被封杀（方法就是防火墙在TCP连接握手时发送连接重置RST伪装包导致连接中断）
#跟踪服务器（4000）
#173.244.217.42 tracker1.resilio.com
#209.95.56.60 tracker2.resilio.com

目前只能用代理才能解决。
或者官方增加更多的tracker服务器。
