### ISSUE TITLE
Youtube的很多视频无法观看

### ISSUE THREAD

**Issue by wangye520** [sy618/hosts#4]
Youtube的很多视频无法观看,
比如
https://www.youtube.com/watch?v=wldrj2nAmrQ
https://www.youtube.com/watch?v=oA0q8_Uo05o
很多关于青云志的视频都无法加载
求解决

**Comment by sy618** [comment]
你所反馈的视频其实在hosts里已经有添加了。
造成不能播放的原因：
有些视频的服务器不支持反代，这个需要对应正确服务器的IP才能看，众所周知，这部分IP已被墙。
大部分视频支持反代，但因反代服务器所在地区有版权问题而被谷歌服务器拒绝访问。
so，只能挂VPN了。

**Comment by wangye520** [comment]
好吧,谢谢大神,一直在用你的hosts,继续加油额
