### ISSUE TITLE
Google Play貌似可以在大陆直连了

### ISSUE THREAD

**Issue by WA-YI** [sy618/hosts#44]
今天下午看到的新闻，Google Play在大陆可以直连了。
测试了一下裸连，截止目前确实还可以直接加载Google Play网页版，因为没安卓机所以APP没测试。
DNS的解析结果为218.254.1.15，测试环境是北京联通和北京电信。

**Comment by sy618** [comment]
似曾相识的IP..
/手动滑稽

**Comment by WA-YI** [comment]
哈 _(:з」∠)_ 忘了清缓存，尴尬。
不过真的可以了，刚也用chinaz试了一下

**Comment by WA-YI** [comment]
哈 _(:з」∠)_ 缓存忘了清，尴尬。
不过真的可以了，刚也用chinaz试了一下

**Comment by sy618** [comment]
是可以了，已经更新了。
不过在我看来应该是大炮在维护中。

**Comment by sy618** [comment]
大炮已维护完毕，我这里测试谷歌官方IP被持续的干扰与丢包。

中国大陆地区解析的谷歌官方IP：
216.58.200.238
216.58.200.46
172.217.24.14
172.217.27.142
可以自己去替换测试。

**Comment by ADGAYMILK** [comment]
上网要戴Tor
