### ISSUE TITLE
hosts pc可以访问youtube，但是路由器版手机，电脑均无法打开youtube视屏

### ISSUE THREAD

**Issue by xuhui0607** [sy618/hosts#48]
修改电脑hosts可以正常访问youtube视屏，但是路由器版dnsmasq,手机，电脑均只能打开youtube主页,点击后视屏无法打开，转呀转。请大牛解决路由器版dnsmasq

**Comment by sy618** [comment]
你测试下这个能否正常打开？
https://vimeo.com/

**Comment by xuhui0607** [comment]
https://vimeo.com/ 可以打开,显示正常。
现在youtube连主页都打不开了，昨天还能打开主页呢，就是内容打不开，转呀转，我现在PING 216.58.200.192不通，显示请求超时！！！

**Comment by child9527** [comment]
我的也一样，ping不通216.58.200.192。所以google、youtube、tumblr都无法访问。

**Comment by sy618** [comment]
已更
tumblr也能打开吧

**Comment by child9527** [comment]
tumblr可以打开，219.76.4.83也能ping通。但是google和youtube说我访问的不是私密连接。要我稍后再试。

**Comment by xuhui0607** [comment]
还是不行，跟前天一个样，youtube主页能打开，内容转呀转，打不开

**Comment by xuhui0607** [comment]
https://www.youtube.com/watch?v=H-cBvaarkg0
这是测式的内容/

**Comment by sy618** [comment]
路由器版再测试一下。

**Comment by xuhui0607** [comment]
我现在用的是PC，晚上才能路由器。

**Comment by sy618** [comment]
有什么问题就到tg群里说。

**Comment by xuhui0607** [comment]
群号发一下，我不在群里

**Comment by xuhui0607** [comment]
youtube还是上不了

**Comment by child9527** [comment]
我也不知道群号。。。

**Comment by sy618** [comment]
README.md 最下面

**Comment by xuhui0607** [comment]
tg下载了，输入手机车进不了
