### ISSUE TITLE
大大，请问如何在自动更新hosts文件的同时，转换为dnsmasq格式的呢

### ISSUE THREAD

**Issue by chonghua** [sy618/hosts#5]
据说dnsmasq解析快一点

**Comment by sy618** [comment]
自动转换我不知道。不过可以再搞个dnsmasq源专用于路由器使用。

目前我用路由器hosts已经能满足使用了，效率低点也看不出来会卡网。所以就没再做个dnsmasq源。

**Comment by sy618** [comment]
https://github.com/vokins/yhosts/issues/28
