### ISSUE TITLE
你的host把github墙了

### ISSUE THREAD

**Issue by child9527** [sy618/hosts#51]
/opt/etc/dnsmasq.d下有dnsfq.conf，/opt/etc下有FQ。
killall dnsmasq，则可以访问github。若killall dnsmasq && dnsmasq -H /opt/etc/FQ，则打不开github。即使删除FQ里的192.30.253.118 gist.github.com，然后再killall dnsmasq && dnsmasq -H /opt/etc/FQ也不行。

**Comment by sy618** [comment]
不是很清楚你是什么情况。
路由器端使用dnsfq就够了，不需要再加FQ hosts。

**Comment by child9527** [comment]
不加不行啊，大佬。不加的情况下，youtube始终595Kbps，加了之后10000K以上。

**Comment by child9527** [comment]
为什么会把github墙了？因为我蠢！自作聪明的以为系统会默认加载/tmp/resolv.conf，哪知没有加载。在没有dns的情况下，访问所有的非hosts文件指定的域名都会失败。之所以还能访问YouTube，是因为FQ里指定了IP。所以，修改命令killall -q dnsmasq && dnsmasq -r /tmp/resolv.conf -H /opt/etc/FQ，完美运行。

**Comment by sy618** [comment]
我更一下dnsfq就能看YouTube 了。

FQ hosts别在路由器上用。

**Comment by child9527** [comment]
你别说，加了host之后前所未有的快。我20M小水管跑出了19800Kbps。从来没试过这么快！！！

**Comment by sy618** [comment]
跟hosts没什么关系。dnsfq规则与FQhosts规则效果一样的。没必要重复订阅。
速度快纯粹是午夜使用的人少而已，服务器资源充足。等白天慢死你。

**Comment by child9527** [comment]
并不是这样哦，我刚刚试了停用host只开dnsmasq.conf，还是一样，595kbps。
