### ISSUE TITLE
大佬用的什么路由器

### ISSUE THREAD

**Issue by andy19801210** [sy618/hosts#54]
推荐个路由器

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 360 1505-A02 发送_

**Comment by sy618** [comment]
能刷第三方固件的都行。
我的路由器刷了这个固件：
http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=161324&extra=page%3D1&page=1&mobile=no&mobile=2
