### ISSUE TITLE
download.lineageos.org 失效，建议删除

### ISSUE THREAD

**Issue by xiesunny** [sy618/hosts#56]
9/20的版本，download.lineageos.org 失效，建议删除。
中科大和清华都有lineageos的镜像，速度很快

https://mirrors.ustc.edu.cn/lineageos/full/
https://mirrors.tuna.tsinghua.edu.cn/lineage-rom/full/

**Comment by Bianfuchen** [comment]
毕竟是代理镜像。你不能保证它不存在后门。

**Comment by Bianfuchen** [comment]
45.79.79.211 download.lineageos.org失效的可以用这个。其实这个只是下载站被墙了。下载的时候并不会，貌似官方还给加了中国的mirror

**Comment by sy618** [comment]
45.79.79.211这个IP的443端口以前被封锁的，现在解封了。download.lineageos.org已改回官方IP。

**Comment by Bianfuchen** [comment]
既然已经解封了。那应该不需要这段了吧。可以删了。

**Comment by helloBibo** [comment]
难道hosts就这样告别历史舞台了嘛, 有点小难过

**Comment by sy618** [comment]
其实一些特殊sni IP依旧还可以使用YouTube、Twitter、Facebook，不过因为太少要获取成本变高了。
从现在到开会期间，出一个IP封一个。各位先用ss/SSR吧，也许用着用着就习惯了，自然摆脱对hosts的依赖。/手动滑稽
