### ISSUE TITLE
Tumblr安卓APP首页内容加载失败

### ISSUE THREAD

**Issue by userfromchina** [sy618/hosts#59]
Tumblr安卓APP首页一直转圈，无法加载出内容。搜索、已关注等页面正常，媒体内容可以正常打开，就是首页不行。浏览器访问手机版Tumblr首页时，Dashboard可以正常加载。
请问应该如何查找问题原因？

**Comment by sy618** [comment]
问题找到了。
有因为汤不热app里使用了Facebook的一个广告域名`https://graph.facebook.com/network_ads_common`，而Facebook已经被ca封禁，所以导致一直在加载。

解决办法很简单：删除graph.facebook.com域名，之后加上一行即可。
127.0.0.1 graph.facebook.com

https://raw.githubusercontent.com/sy618/hosts/master/data/tumblr

**Comment by userfromchina** [comment]
这个方法就好使了几天，现在连不上graph.facebook.com就直接报连接出错了，单独让facebook走代理就可以正常使用。感谢您的指点^_^
