### ISSUE TITLE
求大佬出个专门屏蔽广告的路由器hosts脚本

### ISSUE THREAD

**Issue by scllen** [sy618/hosts#61]
建议现有脚本`https://raw.githubusercontent.com/sy618/hosts/master/dnsmasq/sh/setting.sh`里的dnsfq规则删除
~~想稳定还是自建ss靠谱~~
另外请求整合一些去广告规则

1. `https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt`
[出处](http://bbs.kafan.cn/thread-1866845-1-1.html)

2. `https://easylist-downloads.adblockplus.org/easylistchina.txt`
`https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjxlist.txt`
`https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt`
`https://easylist-downloads.adblockplus.org/easyprivacy.txt`
[出处](http://abpchina.org/forum/forum.php?mod=viewthread&tid=29667)

3. `https://raw.githubusercontent.com/JixunMoe/SimpleList/master/build/SimpleList.txt`
[出处](https://jixunmoe.github.io/SimpleList/)

**Comment by sy618** [comment]
其实不建议用太多的广告规则，因为hosts越大，路由器遍历hosts列表耗时越多，会明显影响网络响应速度。
~~而且我发现你提供的那些并不是hosts规则，全部都是abp规则，这些只适用在adbyby/KP上。~~

我个人就只用这一个去广告hosts规则就觉得够用了。`https://raw.githubusercontent.com/vokins/yhosts/master/hosts`

路由器手动订阅hosts教程可以这样：
1. 手动添加到【在 WAN 上行/下行启动后执行】（在自定义脚本里），实现网络连接上时自动更新。也可以直接在命令行里直接运行。
>wget --no-check-certificate https://raw.githubusercontent.com/vokins/yhosts/master/hosts -O /etc/storage/dnsmasq/hosts;restart_dhcpd

2. 手动添加到【定时任务crontab】（在 系统管理→服务→计划任务 (Crontab)里），实现每天定时自动更新。
>02 00 * * * wget --no-check-certificate https://raw.githubusercontent.com/vokins/yhosts/master/hosts -O /etc/storage/dnsmasq/hosts;restart_dhcpd

**Comment by scllen** [comment]
感谢楼主的解答~
对dnsmasq不懂那么多，那些规则都是从浏览器插件ABP里面抄的。。还以为通用呢
