### ISSUE TITLE
还有TG直连的IP吗？之前那个连不上了，谢谢！！！

### ISSUE THREAD

**Issue by xuhui0607** [sy618/hosts#63]
还有TG直连的IP吗？之前那个175.138.65.245连不上了，谢谢！！！

**Comment by sy618** [comment]
关注这个频道获取最新socks节点：
https://t.me/socks5list


11月10日01更新,点击自动设置TG代理
https://t.me/socks?server=216.24.201.203&port=1080
https://t.me/socks?server=211.108.3.235&port=8888
https://t.me/socks?server=181.56.9.161&port=8080
https://t.me/socks?server=110.45.247.229&port=1080
https://t.me/socks?server=123.201.110.194&port=1080
https://t.me/socks?server=84.242.180.162&port=57424
https://t.me/socks?server=103.10.52.83&port=12196
https://t.me/socks?server=103.10.52.83&port=44820
https://t.me/socks?server=47.93.102.246&port=1080
https://t.me/socks?server=89.46.65.63&port=9406
https://t.me/socks?server=210.211.122.94&port=43149
https://t.me/socks?server=213.128.89.184&port=8081
https://t.me/socks?server=209.151.135.126&port=22249
https://t.me/socks?server=37.191.146.151&port=10200
https://t.me/socks?server=47.90.92.92&port=8080
