### ISSUE TITLE
请求大神给予更新

### ISSUE THREAD

**Issue by LDZHQ** [sy618/hosts#7]
尊敬的大神您好，请您原谅我的贪心不足，我用您的源进行FQ，不过就在刚刚，FQ源貌似失灵了，无法像以往一样进行有效的油管观看和谷歌下载，不知道大神什么时候有时间能给予修复？

**Comment by sy618** [comment]
已更。
提醒一下：不要太依赖hosts。尽可能自备vpn或ss代理吧。
