### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by wst4288** [sy618/hosts#8]
大神，用了你的hosts感觉非常好用，但是还有有一些网站打不开是什么原因呢（用ss则可以打开）。还有，你会一直更新下去吗？

**Comment by sy618** [comment]
1.可能hosts里没收录。
2.我主要是做去广告hosts，并不是专门做FQ hosts，毕竟一个人精力有限。你可以选择一些热门的FQ hosts来长期使用。另外提醒一下：不要太依赖hosts。尽可能自备vpn或ss代理吧。
